<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net48</TargetFrameworks>
    <LangVersion>8.0</LangVersion>
    <AssemblyName>GrabTokenAzureAD</AssemblyName>
    <RootNamespace>GrabTokenAzureAD</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Program.cs" />
    <Compile Remove="CombinedGrabber.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Web" />
  </ItemGroup>

</Project>
